genuine-doc:
  enabled: true
  nameOverride: genuine-doc
  podDisruptionBudget:
    enabled: false
  pods:
    strategy:
      type: Recreate
    controller: deployment
    image:
      name: nginx
      tag: "1.23.3"
    ports:
      - containerPort: 80
    additionalContainers:
      - name: rclone
        image: rclone/rclone:1.62.2
        command: ["/bin/sh", "-c", "/scripts/run.bash"]
        volumeMounts:
          - name: config
            mountPath: /config/rclone
          - name: scripts
            mountPath: /scripts
            readOnly: true
          - mountPath: "/data"
            name: data
    volumes:
      - name: config
        secret:
          secretName: rclone-config
          optional: false
      - name: scripts
        configMap:
          name: rclone-script-cm
          defaultMode: 0744
      - name: nginx-cfg
        configMap:
          name: nginx-conf-cm
      - name: nginx-web
        configMap:
          name: nginx-web-cm
      - name: data
        persistentVolumeClaim:
          claimName: rclone-data
    volumeMounts:
      - mountPath: "/data"
        name: data
      - mountPath: "/etc/nginx"
        name: nginx-cfg
      - mountPath: "/www"
        name: nginx-web

  ingress:
    enabled: false
  service:
    enabled: true
    ports:
      - port: 80
        targetPort: 80
        protocol: TCP
        name: http

genuine-api:
  enabled: true
  nameOverride: genuine

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-api

    volumes:
      - name: secret
        secret:
          secretName: basic-authe-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /secrets

      - name: gcp-sa
        mountPath: "/service-account"
        readOnly: true

genuine-worker:
  enabled: true
  nameOverride: genuine-worker

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-worker

    volumes:
      - name: secret
        secret:
          secretName: worker-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /app/Properties

      - name: gcp-sa
        mountPath: "/secrets"
        readOnly: true

    env:
      - name: DbSetting__ConnectionString
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGODB_URL
            optional: false

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secrets/gcp-sa-file.json

  ingress:
    enabled: false
