genuine-api:
  enabled: true
  nameOverride: genuine

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-api

    volumes:
      - name: secret
        secret:
          secretName: basic-authe-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /secrets

      - name: gcp-sa
        mountPath: "/service-account"
        readOnly: true

    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /service-account/gcp-sa-file.json
    
      - name: PORT
        value: "8080"

      - name: DbSetting__ConnectionString
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGODB_URL
            optional: false

      - name: AssetRegistration__SymetricKey
        valueFrom:
          secretKeyRef:
            name: redirect-secret
            key: REDIRECT_KEY
            optional: false

      - name: BasicAuthen__File
        value: "/secrets/credentials.txt"

      - name: AuditLog__Host
        value: "logstash-syslog.logstash-soc.svc.cluster.local"

      - name: AuditLog__Port
        value: "5140"

genuine-worker:
  enabled: true
  nameOverride: genuine-worker

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-worker

    volumes:
      - name: secret
        secret:
          secretName: worker-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /app/Properties

      - name: gcp-sa
        mountPath: "/secrets"
        readOnly: true

    env:
      - name: DbSetting__ConnectionString
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGODB_URL
            optional: false

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secrets/gcp-sa-file.json

  ingress:
    enabled: false
