genuine-api:
  enabled: true
  nameOverride: genuine

  pods:
    replicas: "0"
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-api

    volumes:
      - name: secret
        secret:
          secretName: basic-authe-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /secrets

      - name: gcp-sa
        mountPath: "/service-account"
        readOnly: true

genuine-worker:
  enabled: true
  nameOverride: genuine-worker

  pods:
    replicas: "0"
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-worker

    volumes:
      - name: secret
        secret:
          secretName: worker-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /app/Properties

      - name: gcp-sa
        mountPath: "/secrets"
        readOnly: true

    env:
      - name: DbSetting__ConnectionString
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGODB_URL
            optional: false

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secrets/gcp-sa-file.json

  ingress:
    enabled: false
