genuine-doc:
  enabled: true
  nameOverride: genuine-doc
  podDisruptionBudget:
    enabled: false
  pods:
    strategy:
      type: Recreate
    controller: deployment
    image:
      name: rclone/rclone
      tag: "1.62.2"
    volumes:
      - name: config
        secret:
          secretName: rclone-config
          optional: false
      - name: scripts
        configMap:
          name: rclone-script-cm
          defaultMode: 0744
      - name: data
        persistentVolumeClaim:
          claimName: rclone-data
    volumeMounts:
      - name: config
        mountPath: /config/rclone
      - name: scripts
        mountPath: /scripts
        readOnly: true
      - mountPath: "/data"
        name: data
    command: ["/bin/sh", "-c", "/scripts/run.bash"]

genuine-api:
  enabled: true
  nameOverride: genuine

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-api

    volumes:
      - name: secret
        secret:
          secretName: basic-authe-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /secrets

      - name: gcp-sa
        mountPath: "/service-account"
        readOnly: true

genuine-worker:
  enabled: true
  nameOverride: genuine-worker

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    image:
      name: gcr.io/its-artifact-commons/jenuine-worker

    volumes:
      - name: secret
        secret:
          secretName: worker-secret
          optional: false

      - name: gcp-sa
        secret:
          secretName: gcp-sa
          items:
          - key: gcp-sa-file
            path: gcp-sa-file.json

    volumeMounts:
      - name: secret
        mountPath: /app/Properties

      - name: gcp-sa
        mountPath: "/secrets"
        readOnly: true

    env:
      - name: DbSetting__ConnectionString
        valueFrom:
          secretKeyRef:
            name: mongodb-secret
            key: MONGODB_URL
            optional: false

      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secrets/gcp-sa-file.json

  ingress:
    enabled: false
