apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: keycloak-client-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: keycloak-client-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "KEYCLOAK_CLIENT_SECRET"
      remoteRef:
        key: jenuine-{{ .Values.envAlias }}-keycloak-client-secret
        version: latest
