apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: worker-secret
spec:
  refreshInterval: 1h          # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store     # name of the SecretStore (or kind specified)
  target:
    name: worker-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: "appsettings.json"
      remoteRef:
        key: jenuine-{{ .Values.envAlias }}-worker-appsetting
        version: latest
